version: 2

models:
  - name: stg_sql_server_dbo__addresses
    description: ""
    columns:
      - name: address_id
      - name: zipcode
      - name: country
      - name: desc_address
      - name: state
      - name: _fivetran_deleted
      - name: _fivetran_synced

  - name: stg_sql_server_dbo__order_items
    description: ""
    columns:
      - name: order_item_id
        description: >
          The surrogate key for order_items models, make that unique applying the combination of order_id, product_id and quantity.
        data_tests:
          - unique
          - not_null

      - name: order_id
        description: "The order identifier that belongs order_items"

      - name: product_id
        description: "The product identifier that is in the order_items"

      - name: quantity
        description: "The product quantity in a order"

      - name: is_data_deleted

      - name: loaded_at
        description: >
                    The timestamp that was loaded the staging order-item table
       

  - name: stg_sql_server_dbo__orders
    description: "Order model getting all data from the source "
    columns:
      - name: order_id
        description: "The system order identifier"

      - name: shipping_company
        description: "the name of the shipping service"

      - name: shipping_cost
        description: "the price of the shipping in order"

      - name: address_id
        description: "the address related to delivery"

      - name: order_created_at
        description: "the time that was made the order"

      - name: promo_id
        data_type: varchar
        description: "the system identifier for the promo"

      - name: estimated_delivery_at
        description: "the estimated time of delivery in a utc"

      - name: order_cost
        description: "the price of the order without the shipping and the promo cost"

      - name: user_id
        description: "The user who made de order"

      - name: order_total
        description: "The total of the price including the shipping and the promo cost"

      - name: delivered_at
        description: "The time that was made the delivery in utc"

      - name: tracking_id
        description: "the code for tracking the shippment"

      - name: status
        description: "The order status"

      - name: is_data_deleted
        description: "The status that check if our record data was deleted in the source system (fivetran)"

      - name: loaded_at

  - name: stg_sql_server_dbo__products
    description: "Model that represent the products"
    columns:
      - name: product_id
        description: "the surrogate key for the product, got from the product_id in the source"
        data_tests:
          - unique
          - not_null

      - name: price
        data_type: decimal

      - name: desc_product
        description: "The name of the product"

      - name: inventory

      - name: is_data_deleted
        description: "The status that check if our record data was deleted in the source system (fivetran)"

      - name: loaded_at

  - name: stg_sql_server_dbo__promo
    description: ""
    columns:
      - name: promo_id
        description: "The surrogate key for promo"

      - name: desc_promo
        data_type: varchar
        description: "Descriptions of promo"

      - name: discount_euro
        data_type: decimal
        description: "Promo's discount value."

      - name: promo_status
        description: "Two types of status: active or inactive."

      - name: is_data_deleted
        description: "The status that check if our record data was deleted in the source system (fivetran)"

      - name: loaded_at

  - name: stg_sql_server_dbo__users
    description: "We're gonna theat the user as a customer throughout the project"
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null

      - name: full_name
        description: "The first and lastname of the customer"

      - name: customer_updated_at
        description: "The time in UTC that the register of the customer was updated"

      - name: customer_created_at
        description: "The time in UTC that the customer was created"

      - name: address_id
        description: "Customer address"
        data_tests:
          - relationships:
              to: ref('stg_server_dbo__addresses')
              field: address_id

      - name: phone_number
        description: "Customer's phone number"

      - name: email
        data_type: varchar
        description: "Customer's email"

      - name: is_data_deleted
        description: "The status that check if our record data was deleted in the source system (fivetran)"

      - name: loaded_at