version: 2

models:
  - name: stg_sql_server_dbo__addresses
    description: ""
    columns:
      - name: address_id
        data_type: varchar
        description: ""

      - name: zipcode
        data_type: number
        description: ""

      - name: country
        data_type: varchar
        description: ""

      - name: desc_addres
        data_type: varchar
        description: ""

      - name: state
        data_type: varchar
        description: ""

      - name: _fivetran_deleted
        data_type: boolean
        description: "The status that check if our record data was deleted in the source system (fivetran)"

      - name: _fivetran_synced
        data_type: timestamp_tz
        description: ""

  - name: stg_sql_server_dbo__order_items
    description: ""
    columns:
      - name: order_item_id
        data_type: varchar
        description: >
          The surrogate key for order_items models, make that unique applying the combination of order_id, product_id and quantity.
        data_tests:
          - unique
          - not_null

      - name: order_id
        data_type: varchar
        description: "The order identifier that belongs order_items"

      - name: product_id
        data_type: varchar
        description: "The product identifier that is in the order_items"

      - name: quantity
        data_type: number
        description: "The product quantity "

      - name: _fivetran_deleted
        data_type: boolean
        description: ""

      - name: _fivetran_synced
        data_type: timestamp_tz
        description: ""

  - name: stg_sql_server_dbo__orders
    description: "Order model getting all data from the source "
    columns:
      - name: order_id
        data_type: varchar
        description: "The system order identifier"

      - name: shipping_service
        data_type: varchar
        description: "the name of the shipping service"

      - name: shipping_cost
        data_type: float
        description: "the price of the shipping"

      - name: address_id
        data_type: varchar
        description: "the address related to delivery"

      - name: created_at
        data_type: timestamp_tz
        description: "the time that was made the order"

      - name: promo_id
        data_type: varchar
        description: "the system identifier for the promo"

      - name: estimated_delivery_at
        data_type: timestamp_tz
        description: "the estimated time in timezone"

      - name: order_cost
        data_type: number
        description: "the price of the order without the shipping and the promo cost"

      - name: user_id
        data_type: varchar
        description: "The user who made de orderT"

      - name: order_total
        data_type: number
        description: "The total of the price including the shipping and the promo cost"

      - name: delivered_at
        data_type: timestamp_tz
        description: "The time that was made the delivery in timezone"

      - name: tracking_id
        data_type: varchar
        description: "the code for tracking the shippment"

      - name: status
        data_type: varchar
        description: "The order status"

      - name: _fivetran_deleted
        data_type: boolean
        description: "The status that check if our record data was deleted in the source system (fivetran)"

      - name: _fivetran_synced
        data_type: timestamp_tz
        description: ""

  - name: stg_sql_server_dbo__products
    description: "Model that represent the products"
    columns:
      - name: product_id
        data_type: varchar
        description: "the surrogate key for the product, got from the combination of product_id, price, name"
        data_tests:
          - unique
          - not_null

      - name: price
        data_type: number
        description: ""

      - name: name
        data_type: varchar
        description: ""

      - name: inventory
        data_type: number
        description: ""

      - name: _fivetran_deleted
        data_type: boolean
        description: "The status that check if our record data was deleted in the source system (fivetran)"

      - name: _fivetran_synced
        data_type: timestamp_tz
        description: ""

  - name: stg_sql_server_dbo__promo
    description: ""
    columns:
      - name: promo_sk
        data_type: varchar
        description: ""

      - name: desc_promo
        data_type: varchar
        description: ""

      - name: discount_euro
        data_type: number
        description: ""

      - name: status
        data_type: varchar
        description: ""

      - name: _fivetran_deleted
        data_type: boolean
        description: "The status that check if our record data was deleted in the source system (fivetran)"

      - name: _fivetran_synced
        data_type: timestamp_tz
        description: ""

  - name: stg_sql_server_dbo__users
    description: ""
    columns:
      - name: customer_id
        data_type: varchar
        description: ""

      - name: name
        data_type: varchar
        description: ""

      - name: updated_at
        data_type: timestamp_tz
        description: ""

      - name: address_id
        data_type: varchar
        description: ""

      - name: created_at
        data_type: timestamp_tz
        description: ""

      - name: phone_number
        data_type: varchar
        description: ""

      - name: total_orders
        data_type: number
        description: ""

      - name: email
        data_type: varchar
        description: ""

      - name: _fivetran_deleted
        data_type: boolean
        description: "The status that check if our record data was deleted in the source system (fivetran)"

      - name: _fivetran_synced
        data_type: timestamp_tz
        description: ""